'use strict';
const GAMES={
lights:{name:'Lights Out',category:'Logic',subtitle:'One tap changes everything.',desc:'Turn every light off. Each tap flips its neighbors, too.',help:'Tap a tile to toggle it and its neighbors above, below, left and right. Bright tiles are on. Get the entire board dark to win. Every starting puzzle is solvable; use Hint for a suggested move.',icon:'lights'},
slide:{name:'Sliding Tiles',category:'Spatial',subtitle:'A place for every piece.',desc:'Slide the numbers into order. Give the empty space a purpose.',help:'Tap a numbered tile next to the empty space to slide it. Arrange the numbers from left to right, top to bottom, with the empty space at the bottom-right. Every shuffle is made with legal moves, so it can always be solved.',icon:'slide'},
memory:{name:'Memory Match',category:'Recall',subtitle:'A familiar kind of magic.',desc:'Find the matching pairs. A little attention goes a long way.',help:'Turn over two cards. Matching symbols stay visible; different symbols turn back over. Find every pair to win. One pair of flips counts as one move. There is no time limit.',icon:'memory'},
flood:{name:'Color Flood',category:'Strategy',subtitle:'Make everything one color.',desc:'Start in the top-left. Grow your color across the whole board.',help:'Your territory starts at the top-left tile marked with a star. Choose a color below the board to recolor your territory and absorb touching tiles of that color. Fill the entire board with one color in as few moves as you can. Numbers identify the colors, too.',icon:'flood'}
};
const COLORS=['#d5f578','#83b8da','#b69bdd','#e89b83','#e8c565','#80bca7'];
const SYMBOLS=['✦','☀','☂','♫','☾','♣','♥','◆','☯','♠','✿','⚑','★','●','▲','■','✚','☁'];
const $=id=>document.getElementById(id),copy=x=>JSON.parse(JSON.stringify(x));
let saved={games:{},stats:{},current:'lights'},storageOK=true;
try{const raw=JSON.parse(localStorage.getItem('pocket-puzzles-v1'));if(raw&&raw.games&&raw.stats&&GAMES[raw.current])saved=raw;}catch{}
let current=saved.current,state=null,timeout=null,focusHint=-1;
function save(){if(window.ranked?.active)return;saved.current=current;saved.games[current]=state;try{localStorage.setItem('pocket-puzzles-v1',JSON.stringify(saved));}catch{storageOK=false;}$('save-note').textContent=storageOK?'Saved on this device':'Progress lasts for this visit';}
function adjacent(i,n){const a=[];if(i%n)a.push(i-1);if(i%n<n-1)a.push(i+1);if(i>=n)a.push(i-n);if(i<n*(n-1))a.push(i+n);return a;}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function toggle(s,i){[i,...adjacent(i,s.n)].forEach(j=>s.board[j]=1-s.board[j]);s.solution[i]=1-s.solution[i];}
function region(board,n){let seen=new Set([0]),queue=[0];for(let k=0;k<queue.length;k++)for(const j of adjacent(queue[k],n))if(!seen.has(j)&&board[j]===board[0]){seen.add(j);queue.push(j);}return [...seen];}
function fresh(game,difficulty='easy',round=1){let n=game==='flood'?(difficulty==='easy'?6:9):game==='slide'?(difficulty==='easy'?3:4):game==='memory'?(difficulty==='easy'?4:6):(difficulty==='easy'?4:5);const s={game,difficulty,round,n,board:[],solution:[],history:[],moves:0,won:false,matched:[],flipped:[],initial:null};
if(game==='lights'){s.board=Array(n*n).fill(0);s.solution=Array(n*n).fill(0);shuffle(Array.from({length:n*n},(_,i)=>i)).slice(0,n===4?5:11).forEach(i=>toggle(s,i));if(!s.board.some(Boolean))toggle(s,0);}
if(game==='slide'){s.board=Array.from({length:n*n},(_,i)=>(i+1)%(n*n));let blank=n*n-1,prev=-1;for(let k=0;k<(n===3?55:140);k++){const choices=adjacent(blank,n).filter(i=>i!==prev),next=choices[Math.floor(Math.random()*choices.length)];[s.board[blank],s.board[next]]=[s.board[next],s.board[blank]];prev=blank;blank=next;}if(s.board.every((v,i)=>v===(i+1)%(n*n))){const j=adjacent(blank,n)[0];[s.board[blank],s.board[j]]=[s.board[j],s.board[blank]];}}
if(game==='memory')s.board=shuffle(Array.from({length:n*n},(_,i)=>Math.floor(i/2)));
if(game==='flood')s.board=Array.from({length:n*n},()=>Math.floor(Math.random()*6));
s.initial={board:[...s.board],solution:[...s.solution]};return s;}
function persistHistory(){state.history.push({board:[...state.board],solution:[...state.solution],moves:state.moves});}
function finish(){if(state.won)return;state.won=true;const key=current+':'+state.difficulty;const st=saved.stats[key]||{wins:0,best:null};st.wins++;st.best=st.best===null?state.moves:Math.min(st.best,state.moves);saved.stats[key]=st;}
function testWin(){if(current==='lights'&&!state.board.some(Boolean)||current==='slide'&&state.board.every((v,i)=>v===(i+1)%(state.n*state.n))||current==='memory'&&state.matched.length===state.board.length||current==='flood'&&state.board.every(v=>v===state.board[0]))finish();}
function choose(game){if(window.ranked?.active)return window.ranked.selectGame(game);clearTimeout(timeout);timeout=null;if(state){if(state.flipped.length===2)state.flipped=[];save();}current=game;focusHint=-1;state=saved.games[game]||fresh(game);if(state.flipped.length===2)state.flipped=[];$('difficulty').value=state.difficulty;render();save();}
function render(message){const g=GAMES[current],n=state.n;document.querySelectorAll('.game-card').forEach(b=>{b.classList.toggle('active',b.dataset.game===current);b.setAttribute('aria-pressed',b.dataset.game===current?'true':'false');});$('eyebrow').textContent=String(Object.keys(GAMES).indexOf(current)+1).padStart(2,'0')+' / '+g.category.toUpperCase();$('game-title').textContent=g.name;$('description').textContent=g.desc;$('instructions').textContent=g.help;$('round-label').textContent='ROUND '+String(state.round).padStart(2,'0');$('moves').textContent=state.moves;$('move-unit').textContent=current==='memory'?'turns':'moves';$('progress').textContent=current==='lights'?state.board.filter(Boolean).length+' lights on':current==='memory'?state.matched.length/2+' / '+state.board.length/2+' pairs':current==='flood'?region(state.board,n).length+' / '+n*n+' tiles':n+' × '+n+' grid';
const board=$('board');board.className='board '+current;board.style.gridTemplateColumns=`repeat(${n}, minmax(0, 1fr))`;board.replaceChildren();
state.board.forEach((v,i)=>{const b=document.createElement(current==='flood'?'div':'button');b.className='tile '+current;const loc='Row '+(Math.floor(i/n)+1)+', column '+(i%n+1);if(current!=='flood'){b.type='button';b.onclick=()=>play(i);b.disabled=state.won;}if(current==='lights'){b.classList.toggle('on',!!v);b.innerHTML='<span class="light-core" aria-hidden="true"></span>';b.setAttribute('aria-label',loc+', light '+(v?'on':'off'));b.setAttribute('aria-pressed',!!v);b.classList.toggle('hinted',i===focusHint);}
if(current==='slide'){b.classList.toggle('empty',v===0);b.textContent=v||'';b.setAttribute('aria-label',v?'Slide tile '+v:'Empty space');if(v===0)b.disabled=true;}
if(current==='memory'){const matched=state.matched.includes(i),visible=matched||state.flipped.includes(i);b.textContent=visible?SYMBOLS[v]:'·';b.classList.toggle('revealed',visible);b.classList.toggle('matched',matched);b.setAttribute('aria-label',loc+(visible?', symbol '+(v+1):', hidden card')+(matched?', matched':''));b.disabled=state.won||visible;}
if(current==='flood'){b.style.background=COLORS[v];b.style.color='#193326';b.textContent=i===0?'★':v+1;b.setAttribute('aria-label',loc+', color '+(v+1));}board.append(b);});
$('palette').hidden=current!=='flood';$('palette').replaceChildren();if(current==='flood')COLORS.forEach((color,i)=>{const b=document.createElement('button');b.style.background=color;b.textContent=i+1;b.setAttribute('aria-label','Flood with color '+(i+1));b.disabled=state.won||i===state.board[0];b.onclick=()=>play(i);$('palette').append(b);});
$('undo').hidden=current==='memory';$('undo').disabled=state.history.length===0||state.won;$('hint').hidden=current!=='lights';$('hint').disabled=state.won;$('new').innerHTML=state.won?'Play another <span aria-hidden="true">＋</span>':'New puzzle <span aria-hidden="true">＋</span>';$('status').classList.toggle('won',state.won);$('status').textContent=state.won?'Nicely done. All solved in '+state.moves+(current==='memory'?' turns.':' moves.'):message||(current==='memory'?'A matching pair is hiding in plain sight.':current==='flood'?'Your territory starts at ★.':current==='slide'?'Make a little room for the next number.':'Find your next bright idea.');const stats=saved.stats[current+':'+state.difficulty];$('record').textContent=stats?stats.wins+' solved · Best: '+stats.best+(current==='memory'?' turns':' moves'):'Your next small win is waiting.';
window.ranked?.afterRender();
}
function play(i){if(window.ranked?.active)return window.ranked.move(i);if(state.won||timeout!==null)return;focusHint=-1;
if(current==='memory'){if(state.matched.includes(i)||state.flipped.includes(i))return;state.flipped.push(i);if(state.flipped.length===2){state.moves++;const [a,b]=state.flipped;if(state.board[a]===state.board[b]){state.matched.push(a,b);state.flipped=[];testWin();}else{timeout=setTimeout(()=>{timeout=null;state.flipped=[];render('A fresh look. Try another pair.');save();},850);}}}
else if(current==='slide'){const blank=state.board.indexOf(0);if(!adjacent(blank,state.n).includes(i)){render('Pick a tile touching the empty space.');return;}persistHistory();[state.board[i],state.board[blank]]=[state.board[blank],state.board[i]];state.moves++;}
else if(current==='lights'){persistHistory();toggle(state,i);state.moves++;}
else{if(i===state.board[0])return;persistHistory();region(state.board,state.n).forEach(j=>state.board[j]=i);state.moves++;}testWin();render();save();}
function restart(){if(window.ranked?.active)return;clearTimeout(timeout);timeout=null;state.board=[...state.initial.board];state.solution=[...state.initial.solution];state.history=[];state.moves=0;state.matched=[];state.flipped=[];state.won=false;focusHint=-1;render('A fresh start. You have this.');save();}
function newPuzzle(difficulty=state.difficulty){if(window.ranked?.active)return window.ranked.selectDifficulty(difficulty);clearTimeout(timeout);timeout=null;state=fresh(current,difficulty,state.round+1);focusHint=-1;render();save();}
Object.entries(GAMES).forEach(([key,g],i)=>{const b=document.createElement('button');b.className='game-card';b.dataset.game=key;b.innerHTML='<span class="mini '+g.icon+'" aria-hidden="true">'+('<i></i>'.repeat(9))+'</span><span><strong>'+g.name+'</strong><small>'+g.subtitle+'</small></span><span class="number">0'+(i+1)+'</span>';b.onclick=()=>choose(key);$('games').append(b);});
$('new').onclick=()=>newPuzzle();$('difficulty').onchange=()=>newPuzzle($('difficulty').value);$('restart').onclick=restart;$('undo').onclick=()=>{if(!state.history.length||state.won)return;const last=state.history.pop();Object.assign(state,last);focusHint=-1;render();save();};$('hint').onclick=()=>{focusHint=state.solution.findIndex(Boolean);render('Try row '+(Math.floor(focusHint/state.n)+1)+', column '+(focusHint%state.n+1)+' — outlined in white.');};
document.querySelector('.brand').onclick=e=>{e.preventDefault();choose('lights');};
choose(current);
if(document.modelContext?.registerTool){
const lifecycle=new AbortController();
const snapshot=()=>({game:current,difficulty:state.difficulty,moves:state.moves,solved:state.won,gridSize:state.n,board:state.board.map((v,i)=>current==='memory'&&!state.matched.includes(i)&&!state.flipped.includes(i)?null:v)});
const definitions=[
{name:'read_puzzle',title:'Read the current puzzle',description:'Read the visible puzzle, moves and completion state. Hidden memory cards stay hidden.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');return snapshot();}},
{name:'select_puzzle',title:'Select a puzzle',description:'Switch to a puzzle, resuming its device-local saved game or starting its first round.',inputSchema:{type:'object',properties:{game:{type:'string',enum:Object.keys(GAMES)}},required:['game'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Object.hasOwn(GAMES,input.game)||Object.keys(input).some(k=>k!=='game'))throw new Error('Choose lights, slide, memory or flood.');choose(input.game);return snapshot();}}
];
for(const tool of definitions){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}
window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}
