import test from 'node:test';
import assert from 'node:assert/strict';
import {localDatabase} from '../scripts/local-db.mjs';
import {handleApi} from '../server/api.js';
import {generate,advance,neighbors,visibleState,dayKey,nextReset} from '../server/game.js';
const now=Date.parse('2026-10-01T10:00:00Z');
function setup(){const DB=localDatabase();return {DB,async call(path,{user='alice',method='GET',body,time=now,origin='https://puzzles.test'}={}){const headers={'Content-Type':'application/json',Origin:origin};if(user){headers['oai-authenticated-user-id']=user;headers['oai-authenticated-user-email']=user+'@test.local';}const r=await handleApi(new Request('https://puzzles.test'+path,{method,headers,...(body?{body:JSON.stringify(body)}:{})}),{DB},time);return {status:r.status,...await r.json()};}};}
async function start(ctx,game='lights',user='alice'){await ctx.call('/api/profile',{user,method:'PUT',body:{name:user}});return ctx.call('/api/start',{user,method:'POST',body:{game,difficulty:'easy'}});}
function solveLights(board,n){for(let mask=0;mask<2**(n*n);mask++){const b=[...board],moves=[];for(let i=0;i<n*n;i++)if(mask&(1<<i)){moves.push(i);for(const j of [i,...neighbors(i,n)])b[j]=1-b[j];}if(!b.some(Boolean))return moves;}throw Error('Unsolvable');}
test('daily generation gives solvable Lights Out and legal slide permutations',()=>{
 for(let k=0;k<12;k++){const lights=generate('lights','easy');const moves=solveLights(lights.board,4);assert.ok(moves.length);let s=lights;for(const i of moves)s=advance(s,i,now);assert.equal(s.won,true);
 for(const difficulty of ['easy','tricky']){const s=generate('slide',difficulty),tiles=s.board.filter(Boolean);let inversions=0;for(let i=0;i<tiles.length;i++)for(let j=i+1;j<tiles.length;j++)inversions+=tiles[i]>tiles[j];const row=s.n-Math.floor(s.board.indexOf(0)/s.n);assert.equal(s.n%2?inversions%2:(inversions+row)%2,s.n%2?0:1);assert.equal(new Set(s.board).size,s.n*s.n);}}
});
test('auth, profile validation and cross-origin protection',async()=>{const c=setup();assert.equal((await c.call('/api/daily?game=lights&difficulty=easy',{user:null})).status,401);assert.equal((await c.call('/api/profile',{method:'PUT',body:{name:'<script>'}})).status,400);assert.equal((await c.call('/api/profile',{method:'PUT',body:{name:'Alice'},origin:'https://evil.test'})).status,403);assert.equal((await c.call('/api/start',{method:'POST',body:{game:'lights',difficulty:'easy'}})).status,409);});
test('shared board, one attempt, ownership and score derived from legal server moves',async()=>{
 const c=setup(),a=await start(c),b=await start(c,'lights','bob');assert.deepEqual(a.attempt.state.board,b.attempt.state.board);assert.equal((await start(c)).attempt.id,a.attempt.id);
 assert.equal((await c.call('/api/move',{user:'bob',method:'POST',body:{attemptId:a.attempt.id,revision:0,index:0}})).status,404);
 let attempt=a.attempt;const moves=solveLights(attempt.state.board,4);for(const [j,index] of moves.entries()){const r=await c.call('/api/move',{method:'POST',time:now+(j+1)*1000,body:{attemptId:attempt.id,revision:attempt.revision,index,moves:0,elapsedMs:0}});assert.equal(r.status,200);attempt=r.attempt;}
 assert.equal(attempt.state.won,true);assert.equal(attempt.state.moves,moves.length);assert.equal(attempt.elapsedMs,moves.length*1000);
 const d=await c.call('/api/daily?game=lights&difficulty=easy');assert.equal(d.leaderboard.mine.rank,1);assert.equal(d.leaderboard.count,1);assert.equal(d.leaderboard.personalBest,moves.length);assert.equal(d.leaderboard.rows[0].name,'alice');assert.equal('player_id' in d.leaderboard.rows[0],false);
 assert.equal((await start(c)).attempt.state.won,true);
});
test('retries are idempotent and stale tabs cannot overwrite a move',async()=>{const c=setup(),a=(await start(c)).attempt;const body={attemptId:a.id,revision:0,index:0};const r=await c.call('/api/move',{method:'POST',body});const repeat=await c.call('/api/move',{method:'POST',body});assert.equal(repeat.attempt.revision,r.attempt.revision);assert.equal(repeat.attempt.state.moves,1);assert.equal((await c.call('/api/move',{method:'POST',body:{...body,index:1}})).status,409);const invalid=await c.call('/api/move',{method:'POST',body:{attemptId:a.id,revision:1,index:-1}});assert.equal(invalid.status,400);});
test('simultaneous moves update at most once',async()=>{const c=setup(),a=(await start(c)).attempt;const results=await Promise.all([0,1].map(index=>c.call('/api/move',{method:'POST',body:{attemptId:a.id,revision:0,index}})));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);});
test('memory deck stays hidden and mismatch delay is enforced',async()=>{const c=setup(),a=(await start(c,'memory')).attempt;assert.ok(a.state.board.every(v=>v===null));const secret=JSON.parse(c.DB.raw.prepare('SELECT state FROM attempts WHERE id=?').get(a.id).state);const i=0,j=secret.board.findIndex(v=>v!==secret.board[i]);const one=await c.call('/api/move',{method:'POST',body:{attemptId:a.id,revision:0,index:i}});assert.equal(one.attempt.state.board.filter(v=>v!==null).length,1);const two=await c.call('/api/move',{method:'POST',body:{attemptId:a.id,revision:1,index:j}});assert.equal(two.attempt.state.moves,1);assert.equal(two.attempt.state.board.filter(v=>v!==null).length,2);const k=secret.board.findIndex((v,k)=>k!==i&&k!==j);assert.equal((await c.call('/api/move',{method:'POST',body:{attemptId:a.id,revision:2,index:k},time:now+100})).status,400);const d=await c.call('/api/daily?game=memory&difficulty=easy',{time:now+1000});assert.ok(d.attempt.state.board.every(v=>v===null));assert.equal((await c.call('/api/move',{method:'POST',body:{attemptId:a.id,revision:2,index:k},time:now+1000})).status,200);});
test('memory and flood can finish through legal moves; invalid slides rejected',()=>{let s=generate('memory','easy');const deck=[...s.board];for(let v=0;v<8;v++)for(let i=0;i<16;i++)if(deck[i]===v)s=advance(s,i,now);assert.equal(s.moves,8);assert.equal(s.won,true);assert.deepEqual(visibleState(s,now).board,deck);s=generate('flood','easy');for(let i=0;i<300&&!s.won;i++)if(s.board[0]!==i%6)s=advance(s,i%6,now);assert.equal(s.won,true);s=generate('slide','easy');assert.throws(()=>advance(s,s.board.indexOf(0),now));});
test('India midnight changes challenge and closes yesterday’s attempt',async()=>{assert.equal(dayKey(Date.parse('2026-10-01T18:29:59Z')),'2026-10-01');assert.equal(dayKey(Date.parse('2026-10-01T18:30:00Z')),'2026-10-02');const c=setup(),a=(await start(c)).attempt;assert.equal((await c.call('/api/move',{method:'POST',time:nextReset('2026-10-01'),body:{attemptId:a.id,revision:0,index:0}})).status,410);});
